language: csharp
solution: CMPE2800DAllanLab02/CMPE2800_Lab02.sln
notifications:
    email:false
  slack: distinctiontaskdp1hq:wbH3X82EhN7b3guGkjAElcEa
  on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"